### ISSUE TITLE
Handle special characters from Python API

### ISSUE THREAD

**Issue by Alex-Monahan** [cwida/duckdb#692]
Hi All!
First off - DuckDB is flat out amazing - I love it. It's perfect for our use case.

I had a small issue while benchmarking it - a registered trademark symbol in my DuckDB caused it to fail upon executing a select statement with the error:
"Runtime error: Could not allocate string object!".

I was planning to adjust the collation, but I couldn't find a function in the Python API to do it. How can I change the collation through Python?

Many thanks!
-Alex

**Comment by Mytherin** [comment]
Glad you are enjoying DuckDB, and thanks for the bug report!

This seems to be a bug in the Python API - DuckDB always supports UTF8 characters. Collations are used only for comparisons and ordering (see [here](https://www.duckdb.org/docs/sql/expressions/collations) for a full explanation). 

Could you provide a (minimal) example of when you encounter the error? And which Python version are you using?

**Comment by Alex-Monahan** [comment]
Ah - let me verify that it is a utf-8 character, and then I will certainly provide more details and an example. Thank you for the link on collations, that helps!

**Comment by Mytherin** [comment]
If it is not too much effort, could you provide an example that triggers this behavior in either case? Even if it's not a bug in the Python API directly the error message should be much more descriptive. I would like to improve that.

**Comment by flevobi** [comment]
Hi, I ran into the same issue with a diffenrent error message: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 0: unexpected end of data `

Here's a testcase:

    import duckdb
    import pandas as pd

    con = duckdb.connect(database=':memory:', read_only=False)
    test_df = pd.DataFrame.from_dict({"i":[1, 2, 3], "j":["a", "c", "ë"]})
    con.register('test_df_view', test_df)
    con.execute('SELECT * FROM test_df_view')

    print(con.fetchall())

On the code above, when I run `print(ord(test_df.iloc[2, 1]))` it prints: `235`

I'm running on Windows 10 with python 3.7.4, duckdb 0.1.9 and pandas 1.0.3.

Thanks, Frans

**Comment by Mytherin** [comment]
Can confirm this unexpectedly throws an exception, seems like a problem in the Python API's handling of strings. I will have a look.

**Comment by Alex-Monahan** [comment]
Thanks for looking into this! I just pulled down duckdb 0.1.9 and replicated the issue I was seeing. I'm using Python 3.7.3 and Pandas 0.24.2. Here is a zipped Jupyter notebook that includes the error messages I'm seeing.

Thanks!
-Alex

[DuckDB Special Characters.zip](https://github.com/cwida/duckdb/files/4820899/DuckDB.Special.Characters.zip)

**Comment by Alex-Monahan** [comment]
#Test register method
db_path = ':memory:'
table_name = 'example_table'
try:
    conn = duckdb.connect(db_path)
    
    conn.register(table_name,df)
    query = "select * from " + table_name

    result_df = conn.execute(query).fetchdf()

finally:
    conn.close()

print(result_df.info())
result_df

![image](https://user-images.githubusercontent.com/52226177/85434671-41ceef00-b53b-11ea-98da-d69f1399bea0.png)

**Comment by Mytherin** [comment]
Apologies for the delay, this should be fixed in the `pyunicode` branch. Could you have a look when you have time if that resolves the problem? Thanks!

**Comment by Alex-Monahan** [comment]
I tried pulling the latest master branch with the command you recommend on your site (pip install duckdb --pre --upgrade), but I am still seeing the same error. This is the version pip said it installed - has this fix just not made its way up to pip yet? No rush - I just wanted to let you know I'm trying to validate your good work!

Message from pip:
Successfully installed duckdb-0.1.10.dev157

Thanks!
-Alex
